name: CI Pipeline
on: [push]
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make test.sh executable
        run: chmod +x ./build.sh
    
      - name: Build application
        run: ./build.sh
